var phrases = [
    "TNETENNBA",
    "Clock speed",
    "Solar flares",
    "Electromagnetic radiation from satellite debris",
    "Static from nylon underwear",
    "Static from plastic slide rules",
    "Global warming",
    "Poor power conditioning",
    "Static buildup",
    "Doppler effect",
    "Hardware stress fractures",
    "Magnetic interference from money/credit cards",
    "Dry joints on cable plug",
    "We're waiting for Comcast to fix that line",
    "We're waiting for CenturyLink to fix that line",
    "Sounds like a Windows problem, try calling Microsoft support",
    "Temporary routing anomaly",
    "Somebody was calculating pi on the server",
    "Fat electrons in the lines",
    "Excess surge protection",
    "Floating point processor overflow",
    "Divide-by-zero error",
    "POSIX compliance problem",
    "Monitor resolution too high",
    "Improperly oriented keyboard",
    "Network packets travelling uphill (use a carrier pigeon)",
    "Decreasing electron flux",
    "First Saturday after first full moon in Winter",
    "Radiosity depletion",
    "CPU radiator broken",
    "Positron router malfunction",
    "Cellular telephone interference",
    "Techtonic stress",
    "Piezo-electric interference",
    "User error",
    "Working as designed",
    "Dynamic software linking table corrupted",
    "Heavy gravity fluctuation, move computer to floor rapidly",
    "Project manager plugged hairdryer into UPS",
    "Not enough memory, go get system upgrade",
    "Interrupt configuration error",
    "Spaghetti cable caused packet failure",
    "Boss forgot system password",
    "Bank holiday - system operating credits  not recharged",
    "Waste water tank overflowed onto computer",
    "Complete Transient Lockout",
    "Bad ether in the cables",
    "Bogon emissions",
    "Change in Earth's rotational speed",
    "Cosmic ray particles crashed through the hard disk platter",
    "Smell from unhygienic janitorial staff wrecked the tape heads",
    "Little hamster in running wheel had coronary; waiting for replacement to be Fedexed from Wyoming",
    "Evil dogs hypnotised the night shift",
    "Plumber mistook routing panel for decorative wall fixture",
    "Electricians made popcorn in the power supply",
    "Groundskeepers stole the root password",
    "High pressure system failure",
    "Failed trials, system needs redesigned",
    "System has been recalled",
    "Not approved by the FCC",
    "Need to wrap system in aluminum foil to fix problem",
    "Not properly grounded, please bury computer",
    "CPU needs recalibration",
    "System needs to be rebooted",
    "Bit bucket overflow",
    "Descramble code needed from software company",
    "Only available on a need to know basis",
    "Knot in cables caused data stream to become twisted and kinked",
    "Nesting roaches shorted out the ether cable",
    "The file system is full of it",
    "You're out of memory",
    "There isn't any problem",
    "Unoptimized hard drive",
    "Typo in the code",
    "Yes, yes, its called a design limitation",
    "Look, buddy:  Windows 3.1 IS A General Protection Fault.",
    "That's a great computer you have there; have you considered how it would work as a BSD machine?",
    "Please excuse me, I have to circuit an AC line through my head to get this database working.",
    "Support staff hung over, send aspirin and come back LATER.",
    "Someone is standing on the ethernet cable, causing a kink in the cable",
    "Windows 95 undocumented 'feature'",
    "Runt packets",
    "Password is too complex to decrypt",
    "Electromagnetic energy loss",
    "Budget cuts",
    "Mouse chewed through power cable",
    "Stale file handle (next time use Tupperware(tm)!)",
    "Feature not yet implemented",
    "Internet outage",
    "Pentium FDIV bug",
    "Vendor no longer supports the product",
    "Small animal kamikaze attack on power supplies",
    "The vendor put the bug there.",
    "SIMM crosstalk.",
    "IRQ dropout",
    "Collapsed Backbone",
    "Power company testing new voltage spike (creation) equipment",
    "Operators on strike due to broken coffee machine",
    "Backup tape overwritten with copy of system manager's favourite EP",
    "UPS interrupted the server's power",
    "The keyboard isn't plugged in",
    "The air conditioning water supply pipe ruptured over the machine room",
    "The electricity substation in the car park blew up.",
    "The rolling stones concert down the road caused a brown out",
    "Forklist drove over the CPU board.",
    "The monitor is plugged into the serial port",
    "Root nameservers are out of sync",
    "Electro-magnetic pulses from French above ground nuke testing.",
    "Your keyboard's space bar is generating spurious keycodes.",
    "The real ttys became pseudo ttys and vice-versa.",
    "The printer thinks its a router.",
    "The router thinks its a printer.",
    "Evil hackers from Serbia.",
    "We just switched to FDDI.",
    "Halon system went off and killed the operators.",
    "User to computer ratio too high.",
    "User to computer ratio too low.",
    "We just switched to Sprint.",
    "It has Intel Inside",
    "Sticky bits on disk.",
    "Power Company having EMP problems with their reactor",
    "The ring needs another token",
    "New management",
    "SCSI Chain overterminated",
    "It's not plugged in.",
    "Because of network lag due to too many people playing deathmatch",
    "You put the disk in upside down.",
    "Daemons loose in system.",
    "BNC (brain not connected)",
    "UBNC (user brain not connected)",
    "Disks spinning backwards - toggle the hemisphere jumper.",
    "New guy cross-connected phone lines with ac power bus.",
    "Had to use hammer to free stuck disk drive heads.",
    "Too few computrons available.",
    "Flat tire on station wagon with tapes.",
    "Communications satellite used by the military for star wars.",
    "Party-bug in the Aloha protocol.",
    "Insert coin for new game",
    "Dew on the telephone lines.",
    "Arcserve crashed the server again.",
    "Some one needed the powerstrip, so they pulled the switch plug.",
    "My pony-tail hit the on/off switch on the power strip.",
    "Big to little endian conversion error",
    "Dumb terminal",
    "Zombie processes haunting the computer",
    "Incorrect time synchronization",
    "Defunct processes",
    "Stubborn processes",
    "Non-redundant fan failure ",
    "Monitor VLF leakage",
    "Bugs in the RAID",
    "No any key on keyboard",
    "Root rot",
    "Backbone Scoliosis",
    "/pub/lunch",
    "Excessive collisions & not enough packet ambulances",
    "Le0: no carrier: transceiver cable problem?",
    "Broadcast packets on wrong frequency",
    "Popper unable to process jumbo kernel",
    "NOTICE: alloc: /dev/null: filesystem full",
    "Pseudo-user on a pseudo-terminal",
    "Recursive traversal of loopback mount points",
    "Backbone adjustment",
    "OS swapped to disk",
    "Vapors from evaporating sticky-note adhesives",
    "Sticktion",
    "Short leg on process table",
    "Multicasts on broken packets",
    "Ether leak",
    "Endothermal recalibration",
    "Filesystem not big enough for Jumbo Kernel Patch",
    "Loop found in loop in redundant loopback",
    "System consumed all the paper for paging",
    "Reformatting Page. Wait...",
    "..disk or the processor is on fire.",
    "SCSI's too wide.",
    "Proprietary Information.",
    "Just type 'mv * /dev/null'.",
    "Runaway cat on system.",
    "Did you pay the new Support Fee?",
    "We only support a 1200 bps connection.",
    "We only support a 28000 bps connection.",
    "I'm sorry a pentium won't do, you need an SGI to connect with us.",
    "Post-it Note Sludge leaked into the monitor.",
    "The curls in your keyboard cord are losing electricity.",
    "The monitor needs another box of pixels.",
    "RPC_PMAP_FAILURE",
    "Kernel panic: write-only-memory (/dev/wom0) capacity exceeded.",
    "Write-only-memory subsystem too slow for this machine. Contact your local dealer.",
    "Quantum dynamics are affecting the transistors",
    "Police are examining all internet packets in the search for a narco-net-trafficker",
    "We are currently trying a new concept of using a live mouse.  Unfortunately, one has yet to survive being hooked up to the computer.....please bear with us.",
    "We didn't pay the Internet bill and it's been cut off.",
    "Lightning strikes.",
    "Of course it doesn't work. We've performed a software upgrade.",
    "Change your language to Finnish.",
    "Fluorescent lights are generating negative ions. If turning them off doesn't work, take them out and put tin foil on the ends.",
    "High nuclear activity in your area.",
    "The UPS doesn't have a battery backup.",
    "Recursivity.  Call back if it happens again.",
    "Someone thought The Big Red Button was a light switch.",
    "The mainframe needs to rest.  It's getting old, you know.",
    "I'm not sure.  Try calling the Internet's head office -- it's in the book.",
    "The lines are all busy (busied out, that is -- why let them in to begin with?).",
    "Fatal error right in front of screen",
    "Wrong polarity of neutron flow",
    "Users learning curve appears to be fractal",
    "We had to turn off that service to comply with the CDA Bill.",
    "Ionization from the air-conditioning",
    "TCP/IP UDP alarm threshold is set too low.",
    "The new frame relay network hasn't bedded down the software loop transmitter yet. ",
    "Fanout dropping voltage too much, try cutting some of those little traces",
    "Plate voltage too low on demodulator tube",
    "CPU needs bearings repacked",
    "Too many little pins on CPU confusing it, bend back and forth until 10-20% are neatly removed. Do _not_ leave metal bits visible!",
    "_Rosin_ core solder? But...",
    "Software uses US measurements, but the OS is in metric...",
    "Your cat tried to eat the mouse.",
    "The Borg tried to assimilate your system. Resistance is futile.",
    "It must have been the recent lightning storm",
    "Too much radiation coming from the soil.",
    "Unfortunately we have run out of bits. Don't worry, the next shipment will be coming next week.",
    "Program load too heavy for processor to lift.",
    "Processes running slowly due to weak power supply",
    "Our ISP is having {switching,routing,SMDS,frame relay} problems",
    "We've run out of licenses",
    "Interference from lunar radiation",
    "You need to install an RTFM interface.",
    "That would be because the software doesn't work.",
    "Someone's tie is caught in the printer, and if anything else gets printed, he'll be in it too.",
    "We're upgrading /dev/null",
    "Our POP server was kidnapped by a weasel.",
    "It's stuck in the Web.",
    "The mouse escaped.",
    "All of the packets are empty.",
    "The UPS is on strike.",
    "Neutrino overload on the nameserver",
    "Melting hard drives",
    "Someone has messed up the kernel pointers",
    "The kernel license has expired",
    "Netscape has crashed",
    "The cord jumped over and hit the power switch.",
    "It was OK before you touched it.",
    "Bit rot",
    "U.S. Postal Service",
    "Your Flux Capacitor has gone bad.",
    "The Dilithium Crystals need to be rotated.",
    "The static electricity routing is acting up...",
    "Traceroute says that there is a routing problem in the backbone.  It's not our problem.",
    "The co-locator cannot verify the frame-relay gateway to the ISDN server.",
    "High altitude condensation from U.S.A.F prototype aircraft has contaminated the primary subnet mask. Turn off your computer for 9 days to avoid damaging it.",
    "Lawn mower blade in your fan need sharpening",
    "Electrons on a bender",
    "Telecommunications is upgrading. ",
    "Telecommunications is downgrading.",
    "Telecommunications is downshifting.",
    "Hard drive sleeping. Let it wake up on it's own...",
    "Interference between the keyboard and the chair.",
    "The CPU has shifted, and become decentralized.",
    "Due to the CDA, we no longer have a root account.",
    "We ran out of dial tone and we're and waiting for the phone company to deliver another bottle.",
    "You must've hit the wrong any key.",
    "PCMCIA slave driver",
    "The Token fell out of the ring. Call us when you find it.",
    "The hardware bus needs a new token.",
    "Too many interrupts",
    "Not enough interrupts",
    "The data on your hard drive is out of balance.",
    "Digital Manipulator exceeding velocity parameters",
    "Appears to be a Slow/Narrow SCSI-0 Interface problem",
    "Microelectronic Riemannian curved-space fault in write-only file system",
    "Fractal radiation jamming the backbone",
    "Routing problems on the neural net",
    "IRQ-problems with the Un-Interruptible-Power-Supply",
    "CPU-angle has to be adjusted because of vibrations coming from the nearby road",
    "Emissions from GSM-phones",
    "CD-ROM server needs recalibration",
    "Firewall needs cooling",
    "Asynchronous inode failure",
    "Transient bus protocol violation",
    "Incompatible bit-registration operators",
    "Your process is not ISO 9000 compliant",
    "You need to upgrade your VESA local bus to a MasterCard local bus.",
    "The recent proliferation of Nuclear Testing",
    "Internet exceeded maximum users, please wait until a user logs off before attempting to log back on.",
    "Your EMAIL is now being delivered by the USPS.",
    "Your computer hasn't been returning all the bits it gets from the Internet.",
    "You've been infected by the Telescoping Hubble virus.",
    "Scheduled global CPU outage",
    "Your Pentium has a heating problem - try cooling it with ice cold water.(Do not turn off your computer, you do not want to cool down the Pentium Chip while he isn't working, do you?)",
    "Your processor has processed too many instructions.  Turn it off immediately, do not type any commands!!",
    "Your packets were eaten by the terminator",
    "Your processor does not develop enough heat.",
    "We need a licensed electrician to replace the light bulbs in the computer room.",
    "The POP server is out of Coke",
    "Fiber optics caused gas main leak",
    "Server depressed, needs Prozac",
    "Quantum decoherence",
    "Those damn raccoons!",
    "Suboptimal routing experience",
    "A plumber is needed, the network drain is clogged",
    "50% of the manual is in .pdf readme files",
    "The AA battery in the wallclock sends magnetic interference",
    "The xy axis in the trackball is coordinated with the summer solstice",
    "The butane lighter causes the pincushioning",
    "Old inkjet cartridges emanate barium-based fumes",
    "Manager in the cable duct",
    "We'll fix that in the next (upgrade, update, patch release, service pack).",
    "HTTPD Error 666 : BOFH was here",
    "HTTPD Error 4004 : very old Intel cpu - insufficient processing power",
    "The ATM board has run out of 10 pound notes.  We are having a whip round to refill it, care to contribute ?",
    "Network failure -  call NBC",
    "Having to manually track the satellite.",
    "The computer has suffered a memory leak, and we are waiting for it to be topped up.",
    "The rubber band broke",
    "We're on Token Ring, and it looks like the token got loose.",
    "Stray Alpha Particles from memory packaging caused Hard Memory Error on Server.",
    "Paradigm shift...without a clutch",
    "PEBKAC (Problem Exists Between Keyboard And Chair)",
    "The cables are not the same length.",
    "Second-system effect.",
    "Chewing gum on /dev/sd3c",
    "Boredom in the Kernel.",
    "The daemons! the daemons! the terrible daemons!",
    "I'd love to help you -- it's just that the Boss won't let me near the computer. ",
    "Struck by the Good Times virus",
    "YOU HAVE AN I/O ERROR -> Incompetent Operator error",
    "Your parity check is overdrawn and you're out of cache.",
    "Plasma conduit breach",
    "Out of cards on drive D:",
    "Sand fleas eating the Internet cables",
    "Parallel processors running perpendicular today",
    "ATM cell has no roaming feature turned on, notebooks can't connect",
    "Webmasters kidnapped by evil cult.",
    "Failure to adjust for daylight savings time.",
    "Virus transmitted from computer to sysadmins.",
    "Virus due to computers having unsafe sex.",
    "Incorrectly configured static routes on the corerouters.",
    "Forced to support NT servers; sysadmins quit.",
    "Suspicious pointer corrupted virtual machine",
    "It's the InterNIC's fault.",
    "Root name servers corrupted.",
    "Budget cuts forced us to sell all the power cords for the servers.",
    "Someone hooked the twisted pair wires into the answering machine.",
    "Operators killed by year 2000 bug bite.",
    "We've picked COBOL as the language of choice.",
    "Operators killed when huge stack of backup tapes fell over.",
    "Robotic tape changer mistook operator's tie for a backup tape.",
    "Someone was smoking in the computer room and set off the halon systems.",
    "Your processor has taken a ride to Heaven's Gate on the UFO behind Hale-Bopp's comet.",
    "It's an ID-10-T error",
    "Dyslexics retyping hosts file on servers",
    "The Internet is being scanned for viruses.",
    "Your computer's contract is set to expire at midnight.",
    "Bad user karma.",
    "/dev/clue was linked to /dev/null",
    "Increased sunspot activity.",
    "We already sent around a notice about that.",
    "Interference from the Van Allen Belt.",
    "Jupiter is aligned with Mars.",
    "Redundant ACLs. ",
    "Mail server hit by UniSpammer.",
    "Data for intranet got routed through the extranet and landed on the internet.",
    "We are a 100% Microsoft Shop.",
    "What you are experiencing is not a problem; it is an undocumented feature.",
    "Sales staff sold a product we don't offer.",
    "Somebody sent chain letter to all 5000 employees.",
    "Sysadmin didn't hear pager go off due to loud music from bar-room speakers.",
    "Sysadmin accidentally destroyed pager with a large hammer.",
    "Sysadmins unavailable because they are in a meeting talking about why they are unavailable so much.",
    "Route flapping at the NAP.",
    "Computers under water due to SYN flooding.",
    "The vulcan-death-grip ping has been applied.",
    "Electrical conduits in machine room are melting.",
    "Traffic jam on the Information Superhighway.",
    "Radial Telemetry Infiltration",
    "Cow-tippers tipped a cow onto the server.",
    "Tachyon emissions overloading the system",
    "Maintenance window broken",
    "We're out of slots on the server",
    "Sysadmins busy fighting SPAM.",
    "Repeated reboots of the system failed to solve problem",
    "Feature was not beta tested",
    "Domain controller not responding",
    "Someone else stole your IP address, call the Internet detectives!",
    "It's not RFC-822 compliant.",
    "Operation failed because: there is no message for this error (#1014)",
    "Stop bit received",
    "Internet is needed to catch the etherbunny",
    "Network down, IP packets delivered via UPS",
    "Firmware update in the coffee machine",
    "Temporal anomaly",
    "Mouse has out-of-cheese-error",
    "Borg implants are failing",
    "Borg nanites have infested the server",
    "Error: one bad user found in front of screen",
    "Please state the nature of the technical emergency",
    "Internet shut down due to maintenance",
    "Daemon escaped from pentagram",
    "Crop circles in the corn shell",
    "Sticky bit has come loose",
    "Hot Java has gone cold",
    "Cache miss - please take better aim next time",
    "Hash table has termites",
    "Trojan horse ran out of hay",
    "Zombie processes detected, machine is haunted.",
    "Overflow error in /dev/null",
    "Browser's cookie is corrupted -- someone's been nibbling on it.",
    "Mailer-daemon is busy burning your message in hell.",
    "According to Microsoft, it's by design",
    "Vi needs to be upgraded to vii",
    "Greenpeace free'd the mallocs",
    "Astropneumatic oscillations in the water-cooling",
    "Somebody ran the operating system through a spelling checker.",
    "Rhythmic variations in the voltage reaching the power supply.",
    "Keyboard Actuator Failure.  Order and Replace.",
    "Packet held up at customs.",
    "Propagation delay.",
    "High line impedance.",
    "Someone set us up the bomb.",
    "Power surges on the Underground.",
    "Don't worry; it's been deprecated. The new one is worse.",
    "Excess condensation in cloud network",
    "It is a layer 8 problem",
    "The math co-processor had an overflow error that leaked out and shorted the RAM",
    "Leap second overloaded RHEL6 servers",
    "DNS server drank too much and had a hiccup",
];

var excuse = document.getElementById("excuse");
var randomPhraseIndex = Math.round(Math.random() * (phrases.length - 1));
excuse.textContent = phrases[randomPhraseIndex];
